### ISSUE TITLE
Add support for button part

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/playground#13]
We need to have support for a "button" part so we can make it interactive.

**Comment by aykevl** [comment]
Yes, I agree.
I've been thinking about it but buttons are a bit complicated to model because they make and break a connection. This means we'd have to reconstruct the netlist on each press and release. Maybe there is a cheaper way to do it, but I'm still thinking about it.

(This would also be needed to implement reset buttons, which would be a nice feature).

**Comment by aykevl** [comment]
Fixed in 557076557c2b865c27a0f90b549861e3e0c181ba
