### ISSUE TITLE
print doesn't show anything on the console

### ISSUE THREAD

**Issue by conejoninja** [tinygo-org/playground#8]
This doesn't show up in the console
```go
print("ABC") // no output
```

This does
```go
print("ABC\n")  // output: ABC
```

This works
```go
println("ABC") // output: ABC
```

This "too"
```go
print("ABC") 
print("DEF")  // output: ABCDEF
```

**Comment by aykevl** [comment]
Output is only written when you print a newline (or use `println`).
I think it would be a good idea to fix that, the relevant function is here:

https://github.com/tinygo-org/playground/blob/558ca0c3d51a5bf8e00a1c367b598524222d7438/runner.js#L105

**Comment by aykevl** [comment]
The new/refactored playground doesn't have this issue anymore. Now it's a limitation of the TinyGo runtime for WebAssembly:

https://github.com/tinygo-org/tinygo/blob/cf0b7edc78e42038a0bb522b3f1a5b76928e730e/src/runtime/runtime_tinygowasm.go#L41-L50

```go
func putchar(c byte) {
	putcharBuffer[putcharPosition] = c
	putcharPosition++


	if c == '\n' || putcharPosition >= putcharBufferSize {
		putcharIOVec.bufLen = putcharPosition
		fd_write(stdout, &putcharIOVec, 1, &putcharNWritten)
		putcharPosition = 0
	}
}
```

Closing because I don't think there is anything to fix in the playground.
